---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - test/dummy/db/schema.rb
    - test/dummy/db/migrate/*.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*

Style/CommandLiteral:
  EnforcedStyle: mixed

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Layout/LineLength:
  Max: 140
  AutoCorrect: true

Naming/VariableNumber:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/ClassLength:
  Exclude:
    - db/migrate/*.rb

Rails/I18nLocaleAssignment:
  Exclude:
    - test/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - lib/spina/admin/conferences/migration/renaming.rb

Lint/MissingSuper:
  Exclude:
    - app/components/**/*
